// Generated by CoffeeScript 1.6.2
/*

  Multiplexing-demultiplexing of several object streams inside single object
  stream.
*/

var through;

through = require('through');

module.exports = function() {
  var s;

  s = through(function(obj) {
    var name, ss, _ref;

    _ref = obj, name = _ref[0], obj = _ref[1];
    ss = s.streams[name];
    if (!ss) {
      return console.warn("orphaned data for stream " + name);
    } else {
      return ss.emit('data', obj);
    }
  });
  s.streams = {};
  s.createStream = function(name) {
    var ss;

    ss = s.streams[name] = through(function(obj) {
      return s.emit('data', [name, obj]);
    });
    return ss;
  };
  return s;
};
