// Generated by CoffeeScript 1.6.2
/*

  Multiplexing-demultiplexing of several object streams inside single object
  stream.
*/

var through;

through = require('through');

module.exports = function(options) {
  var s;

  if (options == null) {
    options = {};
  }
  /*
  
    Create mux-demux stream.
  
    :param options: Object with options
    :option error: Propagate error on substreams (default ``false``)
  */

  s = through(function(obj) {
    var name, ss, _ref;

    _ref = obj, name = _ref[0], obj = _ref[1];
    ss = s.streams[name];
    if (!ss) {
      return console.warn("orphaned data for stream " + name);
    } else {
      return ss.emit('data', obj);
    }
  });
  s.streams = {};
  s.createStream = function(name) {
    var ss;

    ss = s.streams[name] = through(function(obj) {
      return s.emit('data', [name, obj]);
    });
    s.on('end', function() {
      return ss.emit('end');
    });
    if (options.error) {
      s.on('error', function() {
        return ss.emit('error');
      });
    }
    return ss;
  };
  return s;
};
